name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - id: meta
        name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/3scale/aws-cvpn-pki-manager
          tags: |
            type=semver,pattern={{raw}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
